name: Automated Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04  # 明确指定新版系统
    timeout-minutes: 5     # 设置超时时间

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 使用最新稳定版
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # 推荐使用较新Python版本
          cache: 'pip'  # 启用依赖缓存加速
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium pytest-html webdriver-manager
          
      - name: Run tests
        run: pytest --html=report.html --self-contained-html
        
      - name: Upload report
        uses: actions/upload-artifact@v4  # 必须使用v4版本
        with:
          name: test-report
          path: report.html
          retention-days: 3  # 自动清理旧报告