name: Automated Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pytest selenium requests pytest-html webdriver-manager
      - name: Run tests
        run: pytest --html=report.html
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html
